services:
  api-gateway:
    user: root
    container_name: api-gateway
    build:
      context: ./api-gateway/api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway/api-gateway/ocelot.json:/app/ocelot.json
    depends_on:
      - dictionary-parser
      - authorization-module
      - personal-vocab
      - postgres
      - postgres_pv
    ports:
      - "8090:80"
    networks:
      - backend

  dictionary-parser:
    container_name: dictionary-parser
    build:
      context: ./dictionary-parser
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - backend

  authorization-module:
    container_name: authorization-module
    build:
      context: ./authorization-module
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    environment:
      DB_CONNECTION_STRING: "Server=postgres; Port=5432; Database=glosslore; User Id=postgres; Password=123"

  personal-vocab:
    container_name: personal-vocab
    build:
      context: ./personal-vocab
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      postgres_pv:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: "Server=postgres_pv; Port=5432; Database=personal-vocabulary; User Id=postgres; Password=123"

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: glosslore
    ports:
      - "5454:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_pv:
    container_name: postgres_pv
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: personal-vocabulary
    ports:
      - "5455:5432"
    volumes:
      - postgres-pv-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  postgres-data:
  postgres-pv-data:
